import React from 'react'
import Layout from '@/Layouts/Layout'
import Head from 'next/head'
import { FiChevronRight } from 'react-icons/fi'
import Link from 'next/link'
import { HiAnnotation } from 'react-icons/hi'
import AddressCard from '@/components/Checkout.jsx/AddressCard'
import { MdArrowBackIos } from 'react-icons/md'

const OrderDetails = () => {
  return (
    <Layout>
      <Head>
        <title>Cometics Center Cart_page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='bg-white px-6 pt-3 hidden md:block'>
        <div className="flex items-center gap-2">
          <div className="flex items-center text-[12px] gap-[2px]  font-medium opacity-80 hover:text-bgColor transition transform hover:-translate-x-1 motion-reduce:transition-none motion-reduce:hover:transform-none ">
            <Link href={""} className="uppercase">
              Home
            </Link>
            <FiChevronRight size={12} />
          </div>
          <div className="flex items-center text-[12px] gap-[2px] font-medium opacity-80 hover:text-bgColor transition transform hover:-translate-x-1 motion-reduce:transition-none motion-reduce:hover:transform-none">
            <Link href={""} className="uppercase">
              Profile
            </Link>
            <FiChevronRight size={12} />
          </div>
          <div className="flex items-center text-green-700 text-[12px] gap-[2px] font-medium opacity-80 hover:text-bgColor transition transform hover:-translate-x-1 motion-reduce:transition-none motion-reduce:hover:transform-none">
            <h1 className="uppercase">
              Order Details
            </h1>
            <FiChevronRight size={12} />
          </div>
        </div>
        <div className='mt-4 grid grid-cols-6 gap-4'>
          <div className='col-span-4'>
            <div className='flex items-center gap-12'>
              <span className='flex items-center gap-2'>
                <h1 className='text-[18px] font-semibold text-gray-900'>Order Number</h1>
                <h1 className='text-[18px] font-semibold text-red-600'>#45763521</h1>
              </span>
              <span className='flex items-center gap-2 bg-sky-900 p-1 text-white rounded-sm cursor-pointer'>
                <HiAnnotation />
                <h3 className='text-[12px]'>Message this vendor</h3>
              </span>
            </div>
            <div className='p-4 border shadow rounded mt-4'>
              <div className='grid grid-cols-5'>
                <h1 className='col-span-2 text-[14px] font-medium'>Items Summary</h1>
                <h1 className='text-[14px] font-medium'>Quantity</h1>
                <h1 className='text-[14px] font-medium'>Price</h1>
                <h1 className='text-[14px] font-medium'>Total Price</h1>
              </div>
              <hr className='mt-2' />
              <div className='grid grid-cols-5 mt-2 py-1'>
                <span className='flex items-center gap-2 col-span-2'>
                  <picture>
                    <img src="/demo/p/p1.avif" className='w-14 rounded-sm' alt="" />
                  </picture>
                  <h1 className='text-[12px] font-medium'>American hair gel for women</h1>
                </span>
                <h3 className='text-[12px] font-medium opacity-90 flex items-center'>03</h3>
                <h3 className='text-[12px] font-medium opacity-90 flex items-center'>345 TK</h3>
                <h3 className='text-[12px] font-medium opacity-90 flex items-center'>345 TK</h3>
              </div>
              <div className='grid grid-cols-5 mt-2 py-1'>
                <span className='flex items-center gap-2 col-span-2'>
                  <picture>
                    <img src="/demo/p/p1.avif" className='w-14 rounded-sm' alt="" />
                  </picture>
                  <h1 className='text-[12px] font-medium'>American hair gel for women</h1>
                </span>
                <h3 className='text-[12px] font-medium opacity-90 flex items-center'>03</h3>
                <h3 className='text-[12px] font-medium opacity-90 flex items-center'>345 TK</h3>
                <h3 className='text-[12px] font-medium opacity-90 flex items-center'>345 TK</h3>
              </div>
            </div>
            <div className='p-4 border shadow rounded mt-4'>
              <h1 className='text-[14px] font-medium'>Vendor And Order Details</h1>
              <hr className='mt-2' />
              <span className='flex items-center justify-between mt-2 py-2'>
                <h1 className='text-[12px] font-medium'>Vendor Name</h1>
                <h1 className='text-[12px] font-medium'>Sky Land</h1>
              </span>
              <hr className='mt-2' />
              <span className='flex items-center justify-between mt-2 py-2'>
                <h1 className='text-[12px] font-medium'>Vendor ID</h1>
                <h1 className='text-[12px] font-medium'>#90234923DGE</h1>
              </span>
              <hr className='mt-2' />
              <span className='flex items-center justify-between mt-2 py-2'>
                <h1 className='text-[12px] font-medium'>Type</h1>
                <h1 className='text-[12px] font-medium'>Delivery</h1>
              </span>
              <hr className='mt-2' />
              <span className='flex items-center justify-between mt-2 py-2'>
                <h1 className='text-[12px] font-medium'>Note</h1>
                <h1 className='text-[12px] font-medium'>N/A</h1>
              </span>
            </div>
          </div>
          <div className='col-span-2'>
            <div className="amountSection rounded border shadow mt-[42px] p-3">
              <span className="flex items-center justify-between mt-2">
                <h3 className="text-[15px] font-semibold text-gray-700">
                  Order Summary
                </h3>
                <h3 className="text-[12px] font-medium text-white bg-red-400 p-1 rounded-sm">
                  On The Way
                </h3>
              </span>
              <div className='mt-5'>
                <span className="flex items-center justify-between mt-3">
                  <h3 className="text-[12px] font-semibold text-gray-700">
                    Order Created
                  </h3>
                  <h3 className="text-[12px] font-semibold text-gray-700">
                    Sunday, February 12, 2023
                  </h3>
                </span>
                <span className="flex items-center justify-between mt-3">
                  <h3 className="text-[12px] font-semibold text-gray-700">
                    Order Time
                  </h3>
                  <h3 className="text-[12px] font-semibold text-gray-700">
                    12:45 AM
                  </h3>
                </span>
                <span className="flex items-center justify-between mt-3">
                  <h3 className="text-[12px] font-semibold text-gray-700">
                    Sub Total
                  </h3>
                  <h3 className="text-[12px] font-semibold text-gray-700">
                    234 TK
                  </h3>
                </span>
                <span className="flex items-center justify-between mt-3">
                  <h3 className="text-[12px] font-semibold text-gray-700">
                    Delivery Fee
                  </h3>
                  <h3 className="text-[12px] font-semibold text-gray-700">
                    70 TK
                  </h3>
                </span>
              </div>
              <div className="Message bg-gray-100 rounded shadow p-6 mt-2">
                <h1 className="text-[11px] font-medium text-green-700">
                  How we are calculate shipping cost?
                </h1>
                <h1 className="text-[11px] font-medium opacity-80 mt-2">
                  Delivery method has been applied to your order
                </h1>
              </div>
            </div>
            <div className="rounded border shadow mt-4 p-3">
              <span className="flex items-center justify-between mt-2">
                <h3 className="text-[14px] font-semibold text-gray-700">
                  Total
                </h3>
                <h3 className="text-[12px] font-semibold text-gray-700">
                  3454 TK
                </h3>
              </span>
            </div>
            <div className='mt-5'>
              <AddressCard />
            </div>
          </div>
        </div>
      </div>
      <div className='bg-white'>
        <div className='flex items-center justify-between gap-5 p-3'>
          <MdArrowBackIos size={17} className='' />
          <h5 className='text-[15px] font-semibold text-gray-900'>Order Details</h5>
          <span></span>
        </div>
        <div className='py-5 px-3 bg-gray-100'>
          <div className='flex items-center justify-between'>
            <span className='flex items-center gap-2'>
              <h1 className='text-[13px] font-semibold text-gray-900'>Order No :</h1>
              <h1 className='text-[13px] font-semibold text-green-600'>45763521</h1>
            </span>
            <h1 className='text-[13px] font-semibold text-gray-700'>12-04-2023</h1>
          </div>
          <div className='flex items-center justify-between mt-2'>
            <span className='flex items-center gap-2'>
              <h1 className='text-[12px] font-medium text-gray-800'>Tracking No :</h1>
              <h1 className='text-[12px] font-medium '>#4HY31TBU4353</h1>
            </span>
            <h1 className='text-[13px] font-medium text-green-700'>Delivered</h1>
          </div>
          <h1 className='text-[13px] font-medium text-gray-700 mt-2'>2 Items</h1>
          <div className='mt-3'>
            <div className='grid grid-cols-4 border shadow-sm p-[2px] bg-white'>
              <picture className='col-span-1'>
                <img src="/demo/p/p1.avif" alt="" />
              </picture>
              <div className='col-span-3 pl-2 '>
                <h4 className='text-[12px] font-semibold text-gray-700'>American Hair Gel For Women</h4>
                <h4 className='text-[11px] font-semibold text-gray-600'>Sky Blue</h4>
                <span className='flex items-center gap-3 mt-2'>
                  <h4 className='text-[11px] font-semibold text-gray-700'>Color : <span className='text-black'>Red</span></h4>
                  <h4 className='text-[11px] font-semibold text-gray-700'>Size : <span className='text-black'>L</span></h4>
                  <h4 className='text-[11px] font-semibold text-gray-700'>Qty : <span className='text-black'>02</span></h4>
                </span>
                <span className='flex items-center justify-between mt-2'>
                  <h4 className='text-[11px] font-semibold text-gray-700'>Qty : <span className='text-black'>02</span></h4>
                  <span className='text-[12px] font-semibold text-gray-900'>342 TK</span>
                </span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </Layout>

  )
}

export default OrderDetails