import React, { useState, useEffect } from 'react'
import Layout from '@/Layouts/Layout'
import Head from 'next/head'
import { FiCalendar, FiMail, FiPhone } from 'react-icons/fi'
import Deshboard from '@/components/Profile/Deshboard'
import Profile from '@/components/Profile/Profile'


const UserProfile = () => {
    const [showTab, setShowTab] = useState("deshboard")

    useEffect(() => {
        const storedTab = sessionStorage.getItem("tab");
        if (storedTab) {
          setShowTab(storedTab);
        }
      }, []);
    
      const tabControl = (tab) => {
        setShowTab(tab);
        sessionStorage.setItem("tab", tab);
      };

    return (
        <Layout>
            <Head>
                <title>user account</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className='md:px-3 mt-3'>
                <div className='heading flex items-center justify-between bg-white p-3 md:p-5 rounded shadow-sm'>
                    <div className='flex items-center gap-5 md:gap-2'>
                        <picture>
                            <img src="/avatar.png" className='h-14 w-14 rounded-full mb-7 md:mb-0' alt="" />
                        </picture>
                        <div className='flex flex-col gap-1'>
                            <h5 className='capitalize text-[20px] md:text-gray-800 font-[450] text-bgColor'>sara ali khan</h5>
                            <div className='md:flex items-center gap-3'>
                                <span className='flex items-center gap-2 opacity-80'>
                                    <FiMail size={14} />
                                    <h4 className='text-[13px] font-medium text-green-700 md:text-gray-800'>saraalikhan@gmail.com</h4>
                                </span>
                                <hr className='w-4 rotate-90' />
                                <span className='flex items-center gap-2 opacity-80'>
                                    <FiPhone size={14} />
                                    <h4 className='text-[13px] font-medium text-green-700 md:text-gray-800'>+088 0146575682</h4>
                                </span>
                                <hr className='w-4 rotate-90' />
                                <span className='flex items-center gap-2 '>
                                    <FiCalendar size={14} />
                                    <h4 className='text-[13px] font-medium opacity-80'><span className='opacity-70'>Joined</span> 23 August 2023</h4>
                                </span>
                            </div>
                        </div>
                    </div>
                    <div className='hidden md:block'>
                        <button className='text-[14px] font-semibold text-white bg-bgColor p-2 rounded shadow-md'>Sing Out</button>
                    </div>
                </div>
                <div className='listItems mt-2 bg-white px-5 pt-3 pb-1 flex justify-start items-center overflow-x-auto scroll-smooth gap-6 rounded shadow-sm'>
                    <div onClick={() => tabControl("deshboard")} className='w-fit flex flex-col gap-1 cursor-pointer'>
                        <h3 className='text-[13px] font-medium'>Deshboard</h3>
                        <span className={` ${showTab === "deshboard" ? `duration-500 opacity-100` : `opacity-0`} h-[2px] w-full bg-bgColor`}></span>
                    </div>
                    <div onClick={() => tabControl("profile")} className='w-fit flex flex-col gap-1 cursor-pointer'>
                        <h3 className='text-[13px] font-medium'>Profile</h3>
                        <span className={` ${showTab === "profile" ? `duration-500 opacity-100` : `opacity-0`} h-[2px] w-full bg-bgColor`}></span>
                    </div>
                    <div onClick={() => tabControl("following")} className='w-fit flex flex-col gap-1 cursor-pointer'>
                        <h3 className='text-[13px] font-medium'>Following</h3>
                        <span className={` ${showTab === "following" ? `duration-500 opacity-100` : `opacity-0`} h-[2px] w-full bg-bgColor`}></span>
                    </div>
                    <div onClick={() => tabControl("inbox")} className='w-fit flex flex-col gap-1 cursor-pointer'>
                        <h3 className='text-[13px] font-medium'>Inbox</h3>
                        <span className={` ${showTab === "inbox" ? `duration-500 opacity-100` : `opacity-0`} h-[2px] w-full bg-bgColor`}></span>
                    </div>
                    <div onClick={() => tabControl("order")} className='w-fit flex flex-col gap-1 cursor-pointer'>
                        <h3 className='text-[13px] font-medium whitespace-nowrap'>My Order</h3>
                        <span className={` ${showTab === "order" ? `duration-500 opacity-100` : `opacity-0`} h-[2px] w-full bg-bgColor`}></span>
                    </div>
                </div>
                <div className='contentForm mt-2'>
                    <div className={`${showTab === "deshboard" ? `w-full h-fit` : `hidden`}`}>
                        <Deshboard />
                    </div>
                    <div className={`${showTab === "profile" ? `w-full h-fit` : `hidden`}`}>
                        <Profile />
                        dgfgdfgdf
                    </div>
                    <div className={`${showTab === "following" ? `w-full h-fit` : `hidden`}`}>
                        following
                    </div>
                    <div className={`${showTab === "inbox" ? `w-full h-fit` : `hidden`}`}>
                        Inbox
                    </div>
                    <div className={`${showTab === "order" ? `w-full h-fit` : `hidden`}`}>
                        Myorder
                    </div>
                </div>
            </div>
        </Layout>

    )
}

export default UserProfile