import React from 'react'
import Layout from '@/Layouts/Layout'
import Head from 'next/head'


const AffilateForm = () => {
    return (
        <Layout>
            <Head>
                <title>Affiliate Program</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div>AffilateForm</div>
        </Layout>

    )
}

export default AffilateForm