import React, { useEffect, useState } from 'react'
import Layout from '@/Layouts/Layout'
import Head from 'next/head'
import Bottom from '@/components/PhoneBottom/Bottom'
import AccountInformation from '@/components/Affiliate/AccountInformation'
import WebandAppsList from '@/components/Affiliate/WebandAppsList'
import AffliateProfile from '@/components/Affiliate/AffliateProfile'
import StartAffiliate from '@/components/Affiliate/StartAffiliate'

const AffilateForm = () => {

    const [formTab, setFormTab] = useState("account_information")


    useEffect(() => {
        const storedTab = sessionStorage.getItem("affiliateTab");
        if (storedTab) {
            setFormTab(storedTab);
        }
    }, []);

    
    const AffiliateContent = ({ arg }) => {
        if (arg === "account_information") {
            return <AccountInformation setFormTab={setFormTab} />
        } else if (arg === "webandapps_list") {
            return <WebandAppsList setFormTab={setFormTab} />
        } else if (arg === "affiliate_profile") {
            return <AffliateProfile setFormTab={setFormTab} />
        } else if (arg === "start_affiliate") {
            return <StartAffiliate />
        }
    }

    const tabHandle = (arg) => {
        setFormTab(arg)
    }
    return (
        <Layout>
            <Head>
                <title>Affiliate Program</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className='p-6'>
                <h4 className="text-zinc-800 text-opacity-90 md:text-[25px] font-semibold tracking-wide uppercase flex items-center justify-center">creating your amazon affiliate program</h4>
                <div className='w-8/12 mx-auto'>
                    <div className='w-4/5 mx-auto mt-6 border border-zinc-300 rounded-full bg-zinc-200 flex items-center justify-between h-5 shadow'>
                        <div className='flex flex-col items-center gap-3'>
                            <span className='h-[24px] w-[24px] rounded-full border border-zinc-300 bg-zinc-200 shadow-lg flex items-center justify-center'>
                                <span className={`h-[18px] w-[18px] rounded-full 
                                ${formTab === "account_information" ? `bg-bgColor` : `bg-green-600`} `}></span>
                            </span>
                            <h3 className='absolute 
                            text-sm font-medium mt-[30px] text-zinc-900'>Account Information</h3>
                        </div>
                        <div className='flex flex-col items-center gap-3'>
                            <span className='h-[24px] w-[24px] rounded-full border border-zinc-300 bg-zinc-200 shadow-lg flex items-center justify-center'>
                                <span className={`h-[18px] w-[18px] rounded-full 
                                ${formTab === "webandapps_list" ? `bg-bgColor` : `` || formTab === "affiliate_profile" || "start_affiliate" ? `bg-green-600` : ``}`}></span>
                            </span>
                            <h3 className='absolute 
                            text-sm font-medium mt-[30px]
                            text-zinc-700'>Website & Mobile Apps List</h3>
                        </div>
                        <div className='flex flex-col items-center gap-3'>
                            <span className='h-[24px] w-[24px] rounded-full border border-zinc-300 bg-zinc-200 shadow-lg flex items-center justify-center'>
                                <span className={`h-[18px] w-[18px] rounded-full 
                                ${formTab === "affiliate_profile" ? `bg-bgColor` : `` || formTab === "start_affiliate" ? `bg-green-600` : ``}`}></span>
                            </span>
                            <h3 className='absolute 
                            text-sm font-medium mt-[30px]  text-zinc-700 '>Profile</h3>
                        </div>
                        <div className='flex flex-col items-center gap-3'>
                            <span className='h-[24px] w-[24px] rounded-full border border-zinc-300 bg-zinc-200 shadow-lg flex items-center justify-center'>
                                <span className={`h-[18px] w-[18px] rounded-full 
                                ${formTab === "start_affiliate" ? `bg-bgColor` : ``} `}></span>
                            </span>
                            <h3 className='absolute 
                            text-sm font-medium mt-[30px] text-zinc-700'>Start Affiliate</h3>
                        </div>
                    </div>
                    <div className='mt-14'>
                        <AffiliateContent arg={formTab} />
                    </div>
                </div>
            </div>
            <Bottom />
        </Layout>

    )
}

export default AffilateForm