import React, { useState, useEffect } from "react";
import Head from "next/head";
import Layout from "@/Layouts/Layout";
import Link from "next/link";
import AddressCard from "@/components/Checkout.jsx/AddressCard";
import { AiOutlinePlus, AiOutlineCalendar } from "react-icons/ai";
import InputField from "@/components/ReuseableComponent/BaseInput";
import { RxCross2 } from "react-icons/rx";
import { ToastContainer, toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { errorNotify, successNotify } from "@/Notify/Notify";


const Checkout = () => {
    const [openTab, setOpenTab] = useState("address");
    const [showSSL, setShowSSL] = useState(false);
    const [showAddressModal, setShowAddressModal] = useState(false);
    const [selectCod, setSelectCod] = useState(false)
    const [selectOp, setSelectOp] = useState(false)


    const selectPaymentMedhod = (arg) => {
        if (arg === "cod") {
            setSelectCod(true)
            setSelectOp(false)
            setShowSSL(false)
        }
        if (arg === "op") {
            setSelectCod(false)
            setSelectOp(true)
            setShowSSL(true)
        }

        // setSelectCod(arg === "cod")
        // setSelectOp(arg === "op")
    }
    const [shippingAddress, setShippingAddress] = useState({
        name: '',
        mobile_number: '',
        country: 'Bangladesh',
        division: '',
        distric: '',
        sub_distric: '',
        union: '',
        zip_code: '',
        address: ''
    })

    const handleChange = (e) => {
        const { name, value } = e.target;
        setShippingAddress((prev) => ({
            ...prev,
            [name]: value
        }));
    };

    const { name, mobile_number, country, division, distric, sub_distric, union, zip_code, address } = shippingAddress

    const submitHandle = () => {
        if (name === "" || mobile_number === "" || country === "" || division === "" || distric === "" || sub_distric === "" || union === "" || zip_code === "" || address === "") {
            errorNotify("All Input Field Are Required 🤯")
        } else {
            successNotify("Shipping Address Updated 👌")
            setOpenTab("payment")
        }
    }


    return (
        <Layout>
            <ToastContainer />
            <Head>
                <title>Cometics Center checkout_page</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="bg-white px-2 md:px-6 py-3">
                <h1 className="flex items-center justify-center md:text-[23px] font-semibold text-gray-800 capitalize">
                    shipping address
                </h1>
                <div className="tabSection flex justify-center mt-2 md:mt-4 h-14 md:h-20 pb-2 bg-[#eae9e5] md:rounded shadow-md">
                    <div className="flex items-center">
                        <div className="flex flex-col items-center">
                            <div className="h-7 w-7 md:h-9 md:w-9 bg-green-700 rounded-full flex items-center justify-center cursor-pointer">
                                <picture>
                                    <img src="/SVG/whitecart.svg" className="w-[18px] md:w-5" alt="" />
                                </picture>
                            </div>
                            <h2 className="text-[11px] font-medium text-gray-800 absolute mt-7 md:mt-9">
                                Cart
                            </h2>
                        </div>
                    </div>
                    <div className="flex items-center">
                        <span className="h-[2px] w-[60px] md:w-[100px] bg-green-700"></span>
                        <div className="flex flex-col items-center">
                            <div
                                onClick={() => setOpenTab("address")}
                                className="h-7 w-7 md:h-9 md:w-9 bg-green-700 rounded-full flex items-center justify-center  cursor-pointer"
                            >
                                <picture>
                                    <img src="/SVG/whiteaddress.svg" className="w-[18px] md:w-5" alt="" />
                                </picture>
                            </div>
                            <h2 className="text-[11px] font-medium text-gray-800 absolute mt-7 md:mt-9">
                                Address
                            </h2>
                        </div>
                    </div>
                    <div className="flex items-center">
                        <span className="h-[2px] w-[60px] md:w-[100px] bg-gray-500"></span>
                        <div className="flex flex-col items-center ">
                            <div
                                onClick={() => setOpenTab("payment")}
                                className="h-7 w-7 md:h-9 md:w-9 bg-gray-500 rounded-full flex items-center justify-center cursor-pointer"
                            >
                                <picture>
                                    <img src="/SVG/whitepayment.svg" className="w-[18px] md:w-5" alt="" />
                                </picture>
                            </div>
                            <h2 className="text-[11px] font-medium text-gray-800 absolute mt-7 md:mt-9">
                                Payment
                            </h2>
                        </div>
                    </div>
                    <div className="flex items-center">
                        <span className="h-[2px] w-[60px] md:w-[100px] bg-gray-500"></span>
                        <div className="flex flex-col items-center">
                            <div
                                onClick={() => setOpenTab("confirmation")}
                                className="h-7 w-7 md:h-9 md:w-9 bg-gray-500 rounded-full flex items-center justify-center  cursor-pointer"
                            >
                                <picture>
                                    <img src="/SVG/confirmation.svg" className="w-[18px] md:w-5" alt="" />
                                </picture>
                            </div>
                            <h2 className="text-[11px] font-medium text-gray-800 absolute mt-7 md:mt-9">
                                Confirmation
                            </h2>
                        </div>
                    </div>
                </div>
                <div className="contentSection mt-4">
                    <div className={`shippingAdress  ${openTab === "address" ? `block` : `hidden`}`} >
                        <div className="w-full md:flex md:gap-4">
                            <div className="left md:w-4/6 h-fit bg-[#eae9e5] px-3 py-3 md:px-6 md:p-2 rounded shadow-md">
                                <div className="w-full md:grid grid-cols-2 gap-3 mt-3">
                                    <InputField
                                        type="name"
                                        name="name"
                                        label="Full Name"
                                        value={shippingAddress.name}
                                        onChange={handleChange}
                                        placeholder={"Full name*"}
                                    />
                                    <div className='col-span-1 w-full flex flex-col gap-[2px] mt-2 relative '>
                                        <span className="flex items-center absolute 
                                        mt-[26px]  md:mt-[29px] ml-1">
                                            <picture>
                                                <img src="/SVG/BdFlag.svg" className="w-7 " alt="" />
                                            </picture>
                                            <h2 className="text-[12px] md:text-[13px]">+088</h2>
                                        </span>
                                        <label className='text-[13px] md:text-[14px] opacity-90'>Mobile Number</label>
                                        <input
                                            type="tel"
                                            name="mobile_number"
                                            onChange={handleChange}
                                            value={shippingAddress.mobile_number}
                                            placeholder="Mobile No*"
                                            className="py-[10px] md:py-[10px] w-[100%] flex flex-1 text-[12px] md:text-[13px] pl-[70px] inputOuteLine rounded-md md:rounded-sm bg-white"
                                        />
                                    </div>
                                </div>
                                <div className="grid grid-cols-2 gap-3 md:mt-3">
                                    <div className='col-span-1 flex flex-col gap-[2px] mt-2 relative'>
                                        <picture>
                                            <img src="/SVG/BdFlag.svg" className="w-7 absolute mt-[28px]  md:mt-[30px] ml-1" alt="" />
                                        </picture>
                                        <label className='text-[13px] md:text-[14px] opacity-90'>Country</label>
                                        <input
                                            value={shippingAddress.country}
                                            disabled
                                            className="py-[10px] md:py-[10px] w-[100%] text-[12px] md:text-[13px] pl-10 inputOuteLine rounded-md md:rounded-sm bg-white"
                                        />
                                    </div>
                                    <div className="col-span-1 flex flex-col justify-center mt-[12px]">
                                        <h1 className="text-[13px] md:text-[14px] opacity-90">Division</h1>
                                        <select className="w-[100%] py-[10px] md:py-[9px] px-2 md:px-3 text-[12px] md:text-[13px] focus:outline-none rounded-md md:rounded-sm bg-white"
                                            name="division"
                                            value={shippingAddress.division}
                                            onChange={handleChange}

                                        >
                                            <option value="Dhaka ">Dhaka</option>
                                            <option value="Barisl ">Barisal</option>
                                            <option value="Khulna ">Khulna</option>
                                        </select>
                                    </div>
                                </div>
                                <div className="md:grid grid-cols-2 gap-3 mt-3">
                                    <div className="col-span-1 flex flex-col justify-center mt-[10px]">
                                        <h1 className="text-[13px] md:text-[14px] opacity-90">Distric</h1>
                                        <select className="w-[100%] py-[10px] md:py-[10px] px-2 md:px-3 text-[12px] md:text-[13px] focus:outline-none rounded-md  md:rounded-sm bg-white"
                                            name="distric"
                                            value={shippingAddress.distric}
                                            onChange={handleChange}

                                        >
                                            <option value="Dhaka">Dhaka</option>
                                            <option value="Barisl">Barisal</option>
                                            <option value="Khulna">Khulna</option>
                                        </select>
                                    </div>
                                    <div className="col-span-1 flex flex-col justify-center mt-[10px]">
                                        <h1 className="text-[13px] md:text-[14px] opacity-90 ">Sub Distric</h1>
                                        <select className="w-[100%] py-[10px] md:py-[10px] px-2 md:px-3 text-[12px] md:text-[13px] focus:outline-none rounded-md  md:rounded-sm bg-white"
                                            name="sub_distric"
                                            value={shippingAddress.sub_distric}
                                            onChange={handleChange}
                                        >
                                            <option value="Dhaka ">Dhaka</option>
                                            <option value="Barisl ">Barisal</option>
                                            <option value="Khulna ">Khulna</option>
                                        </select>
                                    </div>
                                </div>
                                <div className="grid grid-cols-2 gap-3 md:mt-3 mb-[10px]">
                                    <div className=" col-span-1 flex flex-col justify-center mt-[10px]">
                                        <h1 className="text-[13px] md:text-[14px] opacity-90 ">Union</h1>
                                        <select className="w-[100%] py-[10px] md:py-[10px] px-2 md:px-3 text-[12px] md:text-[13px] focus:outline-none rounded-md  md:rounded-sm bg-white"
                                            name="union"
                                            value={shippingAddress.union}
                                            onChange={handleChange}

                                        >
                                            <option value="Dhaka ">Dhaka</option>
                                            <option value="Barisl ">Barisal</option>
                                            <option value="Khulna ">Khulna</option>
                                        </select>
                                    </div>
                                    <InputField
                                        type="number"
                                        name="zip_code"
                                        label="Zip code"
                                        value={shippingAddress.zip_code}
                                        onChange={handleChange}
                                        placeholder={"Zip Code*"}
                                    />
                                </div>
                                <div className='flex flex-col '>
                                    <label className='text-[13px] md:text-[14px] opacity-90 '>Address</label>
                                    <input
                                        placeholder="Address*"
                                        name="address"
                                        onChange={handleChange}
                                        value={shippingAddress.address}
                                        className="py-[10px] md:py-[10px] w-full text-[12px] md:text-[13px] pl-2 md:pl-4 inputOuteLine rounded-md md:rounded-sm bg-white"
                                    />
                                </div>
                            </div>
                            <div className="right mt-2 md:mt-0 md:w-2/6 h-fit">
                                <div className="productsCard bg-[#eae9e5] rounded shadow-md p-4">
                                    <h3 className="text-[13px] font-medium text-gray-700">
                                        Order Items
                                        <span className="text-[12px] opacity-80">(6)</span>
                                    </h3>
                                    <div className="h-[2px] w-[96px] bg-gray-700 mt-1"></div>
                                    <div className="Card mt-3 ">
                                        <div className="mt-2 grid grid-cols-6 gap-3 bg-gray-100 p-2 rounded-md shadow">
                                            <picture className="col-span-1">
                                                <img
                                                    src="/product1.avif"
                                                    className="rounded-sm"
                                                    alt=""
                                                />
                                            </picture>
                                            <div className="col-span-3 flex flex-col justify-center">
                                                <h3 className="text-[11px] font-semibold text-gray-700">
                                                    European Beauty Mackup
                                                </h3>
                                                <h3 className="text-[11px] font-medium text-gray-700">
                                                    <span className="opacity-80">Color :</span> Red and
                                                    white
                                                </h3>
                                            </div>
                                            <div className="col-span-2 flex flex-col justify-center">
                                                <span className="flex items-center gap-1">
                                                    <h3 className="text-[11px] font-medium text-gray-700">
                                                        &#2547; 236{" "}
                                                    </h3>
                                                    <picture>
                                                        <img
                                                            src="/SVG/multi.svg"
                                                            className="h-2"
                                                            alt=""
                                                        />
                                                    </picture>
                                                    <h3 className="text-[11px] font-medium text-gray-700">
                                                        1
                                                    </h3>
                                                </span>
                                                <h3 className="text-[11px] font-semibold text-gray-700">
                                                    &#2547; 236
                                                </h3>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div className="cuponCard bg-[#eae9e5] rounded shadow-md p-4 mt-4">
                                    <h3 className="text-[13px] font-medium text-gray-700">
                                        Coupon Code
                                        <span className="text-[12px] opacity-80">(6)</span>
                                    </h3>
                                    <div className="h-[2px] w-[96px] bg-gray-700 mt-1"></div>
                                    <div className="mt-3">
                                        <div className="mt-4 flex items-center gap-3">
                                            <input
                                                type="text"
                                                placeholder="Gift card or discount code"
                                                className="w-full py-2 pl-4 border border-gray-300 bg-gray-100 focus:outline-none rounded  text-[12px] font-medium"
                                            />
                                            <button className="px-3 py-2 bg-gray-800 text-white rounded shadow-md text-xs ">
                                                Apply
                                            </button>
                                        </div>
                                    </div>
                                </div>
                                <div className="amountSection bg-[#eae9e5] rounded shadow-md p-4 mt-4">
                                    <div className="bg-gray-100 p-6 rounded-md">
                                        <span className="flex items-center justify-between mt-2">
                                            <h3 className="text-[12px] font-semibold text-gray-700">
                                                Sub Total
                                            </h3>
                                            <h3 className="text-[12px] font-medium text-gray-700">
                                                &#2547; 343
                                            </h3>
                                        </span>
                                        <span className="flex items-center justify-between mt-2">
                                            <h3 className="text-[12px] font-semibold text-gray-700">
                                                Shipping Cost
                                            </h3>
                                            <h3 className="text-[12px] font-medium text-gray-700">
                                                &#2547; 60
                                            </h3>
                                        </span>
                                        <span className="flex items-center justify-between mt-2">
                                            <h3 className="text-[12px] font-semibold text-gray-700">
                                                Tax
                                            </h3>
                                            <h3 className="text-[12px] font-medium text-gray-700">
                                                &#2547; 22
                                            </h3>
                                        </span>
                                        <span className="flex items-center justify-between mt-2">
                                            <h3 className="text-[12px] font-semibold text-gray-700">
                                                Discount
                                            </h3>
                                            <h3 className="text-[12px] font-medium text-gray-700">
                                                &#2547; 30
                                            </h3>
                                        </span>
                                        <hr className="w-full bg-gray-600 mt-3" />
                                        <span className="flex items-center justify-between mt-2">
                                            <h3 className="text-[16px] font-semibold text-gray-700">
                                                Total
                                            </h3>
                                            <h3 className="text-[16px] font-semibold text-gray-700">
                                                &#2547; 30
                                            </h3>
                                        </span>
                                    </div>
                                    <div className="Message bg-gray-100 rounded shadow-md p-6 mt-4">
                                        <h1 className="text-[11px] font-medium text-green-700">
                                            How we are calculate shipping cost?
                                        </h1>
                                        <h1 className="text-[11px] font-medium opacity-80 mt-2">
                                            Express Delivery method has been applied to your order
                                        </h1>
                                    </div>
                                </div>
                                <div
                                    onClick={() => submitHandle()}
                                    className="flex items-center justify-center p-3 w-full text-xs font-medium bg-bgColor text-white mt-2 rounded shadow-md cursor-pointer"
                                >
                                    Proceed To Payment
                                </div>
                            </div>
                        </div>
                    </div>

                    <div className={`paymentDetails   ${openTab === "payment" ? `block` : `hidden`} `}>
                        <div className="w-full md:flex md:gap-4">
                            <div className="left md:w-4/6 h-fit bg-[#eae9e5] px-7 py-4 rounded shadow-md md:flex justify-center md:gap-12">
                                <div className="left_LeftSide">
                                    <h1 className="text-[12px] font-medium text-gray-800 capitalize mb-3">
                                        select your billing address
                                    </h1>
                                    <AddressCard />

                                    <div className="mt-3 md:mt-5">
                                        <h3 className="text-[11px] font-medium text-gray-700">
                                            Order Note :
                                            <span className="opacity-70"> (Optional)</span>
                                        </h3>
                                        <textarea
                                            name=""
                                            placeholder="Special note for your order eg. about delivery"
                                            className="mt-3 w-full h-[60px] md:h-[80px] resize-none focus:outline-none text-[11px] p-2 rounded-sm shadow-sm bg-gray-100"
                                        ></textarea>
                                    </div>
                                </div>
                                <div className="left_RightSide">
                                    <h1 className="text-[12px] font-medium text-gray-800 capitalize mb-3">
                                        select prefered payment method
                                    </h1>
                                    <div onClick={() => selectPaymentMedhod("cod")} className={`p-3 border 
                                    ${selectCod ? `border-bgColor` : `border-gray-400`}  rounded flex items-center gap-4 mt-3 cursor-pointer`}>
                                        <span className="h-4 w-4 p-[2px] rounded-full border border-gray-700 ">
                                            {selectCod && (
                                                <picture>
                                                    <img src="/SVG/correct.svg" alt="" />
                                                </picture>
                                            )}
                                        </span>
                                        <h3 className="text-[11px] font-medium text-gray-700">
                                            Cash on delivery
                                        </h3>
                                        <picture>
                                            <img src="/SVG/cod.svg" className="w-5" alt="" />
                                        </picture>
                                    </div>
                                    <div onClick={() => selectPaymentMedhod("op")} className={`p-3 border 
                                    ${selectOp ? `border-bgColor` : `border-gray-400`}  rounded flex items-center gap-4 mt-3 cursor-pointer`}>
                                        <span className="h-4 w-4 p-[2px] rounded-full border border-gray-700 ">
                                            {selectOp && (
                                                <picture>
                                                    <img src="/SVG/correct.svg" alt="" />
                                                </picture>
                                            )}
                                        </span>
                                        <h3 className="text-[11px] font-medium text-gray-700">
                                            Online Payment
                                        </h3>
                                        <picture>
                                            <img src="/SVG/online.svg" className="w-5" alt="" />
                                        </picture>
                                    </div>
                                 
                                        <picture>
                                            <img src="/ssl/payment.jpg"
                                                className={`${showSSL ? `w-64 h-36 ease-in-out transition-all duration-500` : `h-0 w-0 ease-in-out transition-all duration-500`}  shadow-md rounded mt-2 cursor-pointer mx-auto`} alt=""
                                            />
                                        </picture>
                            


                                </div>
                            </div>
                            <div className="right bg-[#eae9e5] rounded shadow-md mt-2 md:mt-0 md:w-2/6 h-fit">
                                <div className="productsCard rounded p-4">
                                    <h3 className="text-[13px] font-medium text-gray-700">
                                        Order Items
                                        <span className="text-[12px] opacity-80">(6)</span>
                                    </h3>
                                    <div className="h-[1px] w-[96px] bg-gray-600 mt-1">
                                    </div>
                                    <div className="Card">
                                        <div className="mt-2 grid grid-cols-6 gap-3 p-2 border border-gray-400 border-opacity-70 rounded-md">
                                            <picture className="col-span-1">
                                                <img
                                                    src="/product1.avif"
                                                    className="rounded-sm"
                                                    alt=""
                                                />
                                            </picture>
                                            <div className="col-span-3 flex flex-col justify-center">
                                                <h3 className="text-[11px] font-semibold text-gray-700">
                                                    European Beauty Mackup
                                                </h3>
                                                <h3 className="text-[11px] font-medium text-gray-700">
                                                    <span className="opacity-80">Color :</span> Red and
                                                    white
                                                </h3>
                                            </div>
                                            <div className="col-span-2 flex flex-col justify-center">
                                                <span className="flex items-center gap-1">
                                                    <h3 className="text-[11px] font-medium text-gray-700">
                                                        &#2547; 236{" "}
                                                    </h3>
                                                    <picture>
                                                        <img
                                                            src="/SVG/multi.svg"
                                                            className="h-2"
                                                            alt=""
                                                        />
                                                    </picture>
                                                    <h3 className="text-[11px] font-medium text-gray-700">
                                                        1
                                                    </h3>
                                                </span>
                                                <h3 className="text-[11px] font-semibold text-gray-700">
                                                    &#2547; 236
                                                </h3>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div className="addressCard px-4 ">
                                    <h3 className="text-[14px] font-medium text-gray-700">
                                        Coupon Code
                                    </h3>
                                    <div className="h-[1px] w-[96px] bg-gray-600 mt-1">
                                    </div>
                                    <AddressCard />
                                </div>
                                <div className="cuponCard p-4">
                                    <h3 className="text-[14px] font-medium text-gray-700">
                                        Coupon Code
                                    </h3>
                                    <div className="h-[1px] w-[96px] bg-gray-600 mt-1">
                                    </div>
                                    <span className="w-full flex items-center  justify-between gap-2 py-2 px-4 border border-gray-400 border-opacity-70 rounded-md mt-2">
                                        <div className="flex items-center gap-2">
                                            <picture>
                                                <img src="/SVG/coupon.svg" className="w-5" alt="" />
                                            </picture>
                                            <h2 className="text-[12px] font-semibold text-bgColor">#MenomShop </h2>
                                            <span className="text-[11px] font-semibold opacity-70 ml-2">34% off</span>
                                        </div>
                                        <picture>
                                            <img src="/SVG/correctfill.svg" className="w-4" alt="" />
                                        </picture>
                                    </span>

                                </div>
                                <div className="amountSection rounded px-4">
                                    <h3 className="text-[14px] font-medium text-gray-700">
                                        Amount Details
                                    </h3>
                                    <div className="h-[1px] w-[110px] bg-gray-600 mt-1">
                                    </div>
                                    <div className="rounded-md border border-gray-400 border-opacity-70  mt-2 p-4">
                                        <span className="flex items-center justify-between mt-2">
                                            <h3 className="text-[12px] font-semibold text-gray-700">
                                                Sub Total
                                            </h3>
                                            <h3 className="text-[12px] font-semibold text-gray-700">
                                                &#2547; 343
                                            </h3>
                                        </span>
                                        <span className="flex items-center justify-between mt-2">
                                            <h3 className="text-[12px] font-semibold text-gray-700">
                                                Shipping Cost
                                            </h3>
                                            <h3 className="text-[12px] font-semibold  text-gray-700">
                                                &#2547; 60
                                            </h3>
                                        </span>
                                        <span className="flex items-center justify-between mt-2">
                                            <h3 className="text-[12px] font-semibold text-gray-700">
                                                Tax
                                            </h3>
                                            <h3 className="text-[12px] font-semibold  text-gray-700">
                                                &#2547; 22
                                            </h3>
                                        </span>
                                        <span className="flex items-center justify-between mt-2">
                                            <h3 className="text-[12px] font-semibold text-gray-700">
                                                Discount
                                            </h3>
                                            <h3 className="text-[12px] font-semibold  text-gray-700">
                                                &#2547; 30
                                            </h3>
                                        </span>
                                        <div className="w-full h-[1px] bg-gray-600 mt-2"></div>
                                        <span className="flex items-center justify-between mt-2">
                                            <h3 className="text-[16px] font-semibold text-gray-700">
                                                Total
                                            </h3>
                                            <h3 className="text-[16px] font-semibold text-gray-700">
                                                &#2547; 30
                                            </h3>
                                        </span>
                                    </div>
                                    <div className="Message bg-gray-100 rounded shadow-md p-6 mt-4">
                                        <h1 className="text-[11px] font-medium text-green-700">
                                            How we are calculate shipping cost?
                                        </h1>
                                        <h1 className="text-[11px] font-medium opacity-80 mt-2">
                                            Express Delivery method has been applied to your order
                                        </h1>
                                    </div>
                                </div>
                                <div
                                    onClick={() => setOpenTab("payment")}
                                    className="flex items-center justify-center p-3 w-full text-xs font-medium bg-bgColor text-white mt-2 rounded shadow-md cursor-pointer"
                                >
                                    Confirm Order
                                </div>
                            </div>
                        </div>
                    </div>
                    <div className={`orderConfirmation  ${openTab === "confirmation" ? `block` : `hidden`} `}>
                        <div className="w-full md:flex md:gap-6">
                            <div className="left md:w-4/6 md:flex justify-center md:gap-6">
                                <div className="left_LeftSide bg-[#eae9e5] w-full h-fit px-2 md:px-0 md:p-4 rounded shadow-md">
                                    <div className="productsCard rounded p-4">
                                        <h3 className="text-[13px] font-medium text-gray-700">
                                            Order Items
                                            <span className="text-[12px] opacity-80">(6)</span>
                                        </h3>
                                        <div className="h-[1px] w-[96px] bg-gray-600 mt-1">
                                        </div>
                                        <div className="Card">
                                            <div className="mt-2 grid grid-cols-6 gap-3 p-2 border border-gray-400 border-opacity-70 rounded-md">
                                                <picture className="col-span-1">
                                                    <img
                                                        src="/product1.avif"
                                                        className="rounded-sm"
                                                        alt=""
                                                    />
                                                </picture>
                                                <div className="col-span-3 flex flex-col justify-center">
                                                    <h3 className="text-[11px] font-semibold text-gray-700">
                                                        European Beauty Mackup
                                                    </h3>
                                                    <h3 className="text-[11px] font-medium text-gray-700">
                                                        <span className="opacity-80">Color :</span> Red and
                                                        white
                                                    </h3>
                                                </div>
                                                <div className="col-span-2 flex flex-col justify-center">
                                                    <span className="flex items-center gap-1">
                                                        <h3 className="text-[11px] font-medium text-gray-700">
                                                            &#2547; 236{" "}
                                                        </h3>
                                                        <picture>
                                                            <img
                                                                src="/SVG/multi.svg"
                                                                className="h-2"
                                                                alt=""
                                                            />
                                                        </picture>
                                                        <h3 className="text-[11px] font-medium text-gray-700">
                                                            1
                                                        </h3>
                                                    </span>
                                                    <h3 className="text-[11px] font-semibold text-gray-700">
                                                        &#2547; 236
                                                    </h3>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div className="left_RightSide bg-[#eae9e5] w-full h-fit p-2 md:p-4 rounded shadow-md mt-2 md:mt-0">
                                    <div className="addressCard px-4">
                                        <h3 className="text-[14px] font-medium text-gray-700">
                                            Shipping Address
                                        </h3>
                                        <div className="h-[1px] w-[96px] bg-gray-600 mt-1">
                                        </div>
                                        <AddressCard />
                                    </div>
                                    <div className="addressCard px-4 mt-4">
                                        <h3 className="text-[14px] font-medium text-gray-700">
                                            Billing Address
                                        </h3>
                                        <div className="h-[1px] w-[96px] bg-gray-600 mt-1">
                                        </div>
                                        <AddressCard Bill />
                                    </div>
                                </div>
                            </div>
                            <div className="right bg-[#eae9e5] rounded shadow-md mt-2 md:mt-0 md:w-2/6 h-fit px-2 md:px-4 pb-2">
                                <div className="PaymentMethod p-4">
                                    <h3 className="text-[14px] font-medium text-gray-700">
                                        Payment Method
                                    </h3>
                                    <div className="h-[1px] w-[96px] bg-gray-600 mt-1">
                                    </div>
                                    <div className="mt-2 border border-gray-400 border-opacity-70 p-4 rounded-md">
                                        <h1 className="text-[11px] font-medium opacity-80">Cash on delivery</h1>

                                        <span className="flex items-center gap-6 mt-2">
                                            <h1 className="text-[12px] font-medium text-bgColor opacity-80">Due</h1>
                                            <h1 className="text-[12px] font-semibold opacity-80">
                                                &#2547;436</h1>
                                        </span>
                                    </div>
                                </div>
                                <div className="cuponCard px-4">
                                    <h3 className="text-[14px] font-medium text-gray-700">
                                        Coupon Code
                                    </h3>
                                    <div className="h-[1px] w-[96px] bg-gray-600 mt-1">
                                    </div>
                                    <span className="w-full flex items-center  justify-between gap-2 py-2 px-4 border border-gray-400 border-opacity-70 rounded-md mt-2">
                                        <div className="flex items-center gap-2">
                                            <picture>
                                                <img src="/SVG/coupon.svg" className="w-5" alt="" />
                                            </picture>
                                            <h2 className="text-[12px] font-semibold text-bgColor">#MenomShop </h2>
                                            <span className="text-[11px] font-semibold opacity-70 ml-2">34% off</span>
                                        </div>
                                        <picture>
                                            <img src="/SVG/correctfill.svg" className="w-4" alt="" />
                                        </picture>
                                    </span>
                                </div>
                                <div className="amountSection rounded px-4">
                                    <h3 className="text-[14px] font-medium text-gray-700">
                                        Amount Details
                                    </h3>
                                    <div className="h-[1px] w-[110px] bg-gray-600 mt-1">
                                    </div>
                                    <div className="rounded-md border border-gray-400 border-opacity-70  mt-2 p-4">
                                        <span className="flex items-center justify-between mt-2">
                                            <h3 className="text-[12px] font-semibold text-gray-700">
                                                Sub Total
                                            </h3>
                                            <h3 className="text-[12px] font-semibold text-gray-700">
                                                &#2547; 343
                                            </h3>
                                        </span>
                                        <span className="flex items-center justify-between mt-2">
                                            <h3 className="text-[12px] font-semibold text-gray-700">
                                                Shipping Cost
                                            </h3>
                                            <h3 className="text-[12px] font-semibold  text-gray-700">
                                                &#2547; 60
                                            </h3>
                                        </span>
                                        <span className="flex items-center justify-between mt-2">
                                            <h3 className="text-[12px] font-semibold text-gray-700">
                                                Tax
                                            </h3>
                                            <h3 className="text-[12px] font-semibold  text-gray-700">
                                                &#2547; 22
                                            </h3>
                                        </span>
                                        <span className="flex items-center justify-between mt-2">
                                            <h3 className="text-[12px] font-semibold text-gray-700">
                                                Discount
                                            </h3>
                                            <h3 className="text-[12px] font-semibold  text-gray-700">
                                                &#2547; 30
                                            </h3>
                                        </span>
                                        <div className="w-full h-[1px] bg-gray-600 mt-2"></div>
                                        <span className="flex items-center justify-between mt-2">
                                            <h3 className="text-[16px] font-semibold text-gray-700">
                                                Total
                                            </h3>
                                            <h3 className="text-[16px] font-semibold text-gray-700">
                                                &#2547; 30
                                            </h3>
                                        </span>
                                    </div>
                                    <div className="Message bg-gray-100 rounded shadow-md p-6 mt-4">
                                        <h1 className="text-[11px] font-medium text-green-700">
                                            How we are calculate shipping cost?
                                        </h1>
                                        <h1 className="text-[11px] font-medium opacity-80 mt-2">
                                            Express Delivery method has been applied to your order
                                        </h1>
                                    </div>
                                </div>
                                <div
                                    onClick={() => setOpenTab("payment")}
                                    className="flex items-center justify-center p-3 w-full text-xs font-medium bg-bgColor text-white mt-2 rounded shadow-md cursor-pointer "
                                >
                                    Confirm Order
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </Layout>
    );
};

export default Checkout;
