import Head from "next/head";
import Layout from "@/Layouts/Layout";
import Slider from "@/components/Home/SliderSection/Slider";
import Categorie from "@/components/Home/Cetagory/Category";
import AdsSection from "@/components/Home/AdsSection";
import FeaturedProducts from "@/components/Home/Products/Featured/FeaturedProducts";
import PopularProduct from "@/components/Home/Products/TabSection/TabSection";
import TopVendor from "@/components/Home/TopVendor/TopVendor";
import Featured from "@/components/Home/Featured/Featured";
import { useRouter } from "next/router";
import Bottom from "@/components/PhoneBottom/Bottom";
import TopBrand from "@/components/Home/TopBrand/TopBrand";

export default function Home() {
  const { asPath, pathname } = useRouter()
  return (
    <Layout>
      <Head>
        <title>Cometics Center</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="">
        <Slider />
        <Categorie />
        <AdsSection />
        <TopBrand />
        <FeaturedProducts />
        <TopVendor />
        <PopularProduct />
        <AdsSection />
        <Featured />
        <Bottom homePath={pathname} />
      </div>
    </Layout>
  );
}
