import Head from "next/head";
import Layout from "@/Layouts/Layout";
import Slider from "@/components/Home/SliderSection/Slider";
import Categorie from "@/components/Home/Cetagory/Category";
import AdsSection from "@/components/Home/AdsSection";
import FeaturedProducts from "@/components/Home/Products/FeaturedProducts";

export default function Home() {
  return (
    <Layout>
      <Head>
        <title>Agro-Ecommerce</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <script ></script>
      </Head>
      <div className="">
        <Slider />
        <Categorie />
        <AdsSection/>
        <FeaturedProducts/>
      </div>
    </Layout>
  );
}
