import Head from "next/head";
import React from "react";
import { useRouter } from "next/router";
import Layout from "@/Layouts/Layout";
import Bottom from "@/components/PhoneBottom/Bottom";
import CategoryCart from "@/components/Home/Cetagory/CategoryCard";


const catData = [
    {
        id: 1,
        image: "/demo/c/c1.jpg",
        name: "Eyes"
    },
    {
        id: 2,
        image: "/demo/c/c2.avif",
        name: "Hand Wash"
    },
    {
        id: 3,
        image: "/demo/c/c3.avif",
        name: "Nails"
    },
    {
        id: 4,
        image: "/demo/c/c4.avif",
        name: "Hair Care"
    },
    {
        id: 1,
        image: "/demo/c/c1.jpg",
        name: "Eyes"
    },
    {
        id: 2,
        image: "/demo/c/c2.avif",
        name: "Hand Wash"
    },
    {
        id: 3,
        image: "/demo/c/c3.avif",
        name: "Nails"
    },
    {
        id: 4,
        image: "/demo/c/c4.avif",
        name: "Hair Care"
    },
    {
        id: 1,
        image: "/demo/c/c1.jpg",
        name: "Eyes"
    },
    {
        id: 2,
        image: "/demo/c/c2.avif",
        name: "Hand Wash"
    },
    {
        id: 3,
        image: "/demo/c/c3.avif",
        name: "Nails"
    },
    {
        id: 4,
        image: "/demo/c/c4.avif",
        name: "Hair Care"
    },
    {
        id: 2,
        image: "/demo/c/c2.avif",
        name: "Hand Wash"
    },
    {
        id: 3,
        image: "/demo/c/c3.avif",
        name: "Nails"
    },
    {
        id: 4,
        image: "/demo/c/c4.avif",
        name: "Hair Care"
    },
    {
        id: 2,
        image: "/demo/c/c2.avif",
        name: "Hand Wash"
    },
    {
        id: 3,
        image: "/demo/c/c3.avif",
        name: "Nails"
    },
    {
        id: 4,
        image: "/demo/c/c4.avif",
        name: "Hair Care"
    },
]

const MobileCategorieslist = () => {
    const { asPath, pathname } = useRouter()

    return (
        <Layout>
            <Head>
                <title>Cometics Center</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="bg-white">
                <div className="flex items-center p-2">
                    <h1 className="uppercase text-sm font-medium opacity-90">all categories</h1>
                </div>
                <hr className="mt-1" />

                <div className="p-2 flex flex-col gap-2">
                    <div className="w-full">
                        <span className="flex flex-col w-fit">
                            <h1 className="uppercase text-xs font-medium">Face & mackup</h1>
                            <hr className="mt-[6px] w-full" />
                        </span>
                        <div className="mt-1 grid grid-cols-4 sm:grid-cols-5">
                            {catData.map((item) => (
                                <div key={item.id}>
                                    <CategoryCart item={item} />
                                </div>
                            ))}
                        </div>
                    </div>
                </div>
            </div>
            <Bottom categoryPath={pathname} />
        </Layout>
    );
};

export default MobileCategorieslist;
